visible = false;
audio_sound_gain(BGMPlayer.playingTrack,0,1000);
audio_stop_all();
instance_destroy(BGMPlayer);
deleteLivesData();
instance_deactivate_all(true);
//instance_activate_object(MonsterPlayer);
instance_activate_object(JoyPad);
instance_create_layer(x,y,"fadetransition",fadeOut);
fadeOut.changeToRoom = GameTitleMenu;